// <auto-generated />
using System;
using MergeGame.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MergeGame.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MergeGameDbContext))]
    [Migration("20260815025205_AddIdempotentBoardItemSales")]
    partial class AddIdempotentBoardItemSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MergeGame.Server.Domain.Administration.AdminActionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("action");

                    b.Property<string>("AfterValue")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("after_value");

                    b.Property<string>("BeforeValue")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("before_value");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("ascii_bin");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("operator_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<long>("ResultRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("result_revision");

                    b.Property<Guid>("TargetPlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("target_player_id");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_audits_operator_idempotency");

                    b.HasIndex("TargetPlayerId", "CreatedAtUtc")
                        .HasDatabaseName("ix_admin_audits_target_created");

                    b.ToTable("admin_action_audits", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Administration.PlayerModeration", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_suspended");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PlayerId");

                    b.ToTable("player_moderations", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Authentication.RefreshTokenSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash")
                        .UseCollation("ascii_bin");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_token_hash");

                    b.HasIndex("PlayerId", "FamilyId")
                        .HasDatabaseName("ix_refresh_sessions_player_family");

                    b.ToTable("refresh_token_sessions", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardActionReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("ascii_bin");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("response_json");

                    b.Property<int>("SourceSlot")
                        .HasColumnType("int")
                        .HasColumnName("source_slot");

                    b.Property<int>("TargetSlot")
                        .HasColumnType("int")
                        .HasColumnName("target_slot");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_board_action_receipts_player_idempotency");

                    b.ToTable("board_action_receipts", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("chain_id")
                        .UseCollation("ascii_bin");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int")
                        .HasColumnName("slot_index");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("board_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_board_items_slot_index", "`slot_index` >= 0 AND `slot_index` < 35");
                        });
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardItemSaleReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("ascii_bin");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("char(36)")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("response_json");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_board_item_sales_player_idempotency");

                    b.ToTable("board_item_sale_receipts", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.PlayerBoard", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PlayerId");

                    b.ToTable("player_boards", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Economy.PlayerEconomy", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<long>("Coins")
                        .HasColumnType("bigint")
                        .HasColumnName("coins");

                    b.Property<int>("Energy")
                        .HasColumnType("int")
                        .HasColumnName("energy");

                    b.Property<DateTime?>("LastDailyRewardClaimedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_daily_reward_claimed_at_utc");

                    b.Property<DateTime>("LastEnergyUpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_energy_updated_at_utc");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("PlayerId");

                    b.ToTable("player_economies", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_economies_coins", "`coins` >= 0");

                            t.HasCheckConstraint("ck_player_economies_energy", "`energy` >= 0 AND `energy` <= 100");
                        });
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Generators.GeneratorProductionReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("GeneratorId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("generator_id")
                        .UseCollation("ascii_bin");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("ascii_bin");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("response_json");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_generator_receipts_player_idempotency");

                    b.ToTable("generator_production_receipts", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Generators.PlayerGenerator", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<string>("GeneratorId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("generator_id")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("ChargeUpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("charge_updated_at_utc");

                    b.Property<int>("Charges")
                        .HasColumnType("int")
                        .HasColumnName("charges");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("PlayerId", "GeneratorId");

                    b.ToTable("player_generators", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_generators_charges", "`charges` >= 0");
                        });
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("display_name");

                    b.Property<string>("GuestTokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("guest_token_hash")
                        .UseCollation("ascii_bin");

                    b.HasKey("Id");

                    b.HasIndex("GuestTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_players_guest_token_hash");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Quests.GameplayEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<long>("BoardRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("board_revision");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("event_type")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<int>("ResultItemLevel")
                        .HasColumnType("int")
                        .HasColumnName("result_item_level");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "OccurredAtUtc")
                        .HasDatabaseName("ix_gameplay_events_player_time");

                    b.ToTable("gameplay_events", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Quests.PlayerQuest", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<string>("QuestId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("quest_id")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("claimed_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("int")
                        .HasColumnName("current_count");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<long>("RewardCoins")
                        .HasColumnType("bigint")
                        .HasColumnName("reward_coins");

                    b.Property<int>("TargetCount")
                        .HasColumnType("int")
                        .HasColumnName("target_count");

                    b.HasKey("PlayerId", "QuestId");

                    b.ToTable("player_quests", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Quests.RewardClaim", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("quest_id")
                        .UseCollation("ascii_bin");

                    b.Property<long>("RewardCoins")
                        .HasColumnType("bigint")
                        .HasColumnName("reward_coins");

                    b.HasKey("PlayerId", "IdempotencyKey");

                    b.ToTable("reward_claims", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Social.EnergyGift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("GiftDateUtc")
                        .HasColumnType("date")
                        .HasColumnName("gift_date_utc");

                    b.Property<Guid>("RecipientPlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recipient_player_id");

                    b.Property<Guid>("SenderPlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sender_player_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipientPlayerId");

                    b.HasIndex("SenderPlayerId", "RecipientPlayerId", "GiftDateUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_energy_gifts_daily_sender_recipient");

                    b.ToTable("energy_gifts", null, t =>
                        {
                            t.HasCheckConstraint("ck_energy_gifts_distinct_players", "`sender_player_id` <> `recipient_player_id`");
                        });
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Social.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("PlayerHighId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_high_id");

                    b.Property<Guid>("PlayerLowId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_low_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerHighId")
                        .HasDatabaseName("ix_friendships_player_high_id");

                    b.HasIndex("PlayerLowId", "PlayerHighId")
                        .IsUnique()
                        .HasDatabaseName("ux_friendships_player_pair");

                    b.ToTable("friendships", null, t =>
                        {
                            t.HasCheckConstraint("ck_friendships_distinct_players", "`player_low_id` <> `player_high_id`");
                        });
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Social.PlayerSocialProfile", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FriendCode")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("friend_code")
                        .UseCollation("ascii_general_ci");

                    b.HasKey("PlayerId");

                    b.HasIndex("FriendCode")
                        .IsUnique()
                        .HasDatabaseName("ux_social_profiles_friend_code");

                    b.ToTable("player_social_profiles", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Administration.AdminActionAudit", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("TargetPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Administration.PlayerModeration", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("MergeGame.Server.Domain.Administration.PlayerModeration", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Authentication.RefreshTokenSession", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardActionReceipt", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardItem", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Boards.PlayerBoard", null)
                        .WithMany("Items")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardItemSaleReceipt", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.PlayerBoard", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("MergeGame.Server.Domain.Boards.PlayerBoard", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Economy.PlayerEconomy", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("MergeGame.Server.Domain.Economy.PlayerEconomy", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Generators.GeneratorProductionReceipt", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Generators.PlayerGenerator", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Quests.GameplayEvent", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Quests.PlayerQuest", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Quests.RewardClaim", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Social.EnergyGift", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("RecipientPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("SenderPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Social.Friendship", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerHighId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerLowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Social.PlayerSocialProfile", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("MergeGame.Server.Domain.Social.PlayerSocialProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.PlayerBoard", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
