// <auto-generated />
using System;
using MergeGame.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MergeGame.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MergeGameDbContext))]
    [Migration("20260728125033_InitialPlayerSchema")]
    partial class InitialPlayerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MergeGame.Server.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("display_name");

                    b.Property<string>("GuestTokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("guest_token_hash")
                        .UseCollation("ascii_bin");

                    b.HasKey("Id");

                    b.HasIndex("GuestTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_players_guest_token_hash");

                    b.ToTable("players", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
