// <auto-generated />
using System;
using MergeGame.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MergeGame.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MergeGameDbContext))]
    [Migration("20260728130756_AddPlayerBoards")]
    partial class AddPlayerBoards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("chain_id")
                        .UseCollation("ascii_bin");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int")
                        .HasColumnName("slot_index");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_board_items_player_slot");

                    b.ToTable("board_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_board_items_slot_index", "`slot_index` >= 0 AND `slot_index` < 35");
                        });
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.PlayerBoard", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PlayerId");

                    b.ToTable("player_boards", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("display_name");

                    b.Property<string>("GuestTokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("guest_token_hash")
                        .UseCollation("ascii_bin");

                    b.HasKey("Id");

                    b.HasIndex("GuestTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_players_guest_token_hash");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.BoardItem", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Boards.PlayerBoard", null)
                        .WithMany("Items")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.PlayerBoard", b =>
                {
                    b.HasOne("MergeGame.Server.Domain.Players.Player", null)
                        .WithOne()
                        .HasForeignKey("MergeGame.Server.Domain.Boards.PlayerBoard", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MergeGame.Server.Domain.Boards.PlayerBoard", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
